#!/usr/bin/env python3
"""Offline KINEXGM1 frame-count normalization for already-baked motion assets.

Re-bakes a published ``motion.bin`` to the CoachClip frame count without
re-running LHM: the binary is decoded, time-linearly resampled with the same
slerp/lerp rule used at pack time (``backend.avatar_assets``), and atomically
written back.  The original ``motion.bin`` and ``record.json`` are first copied
to ``~/.local/share/kinex/motion-backups/<motionId>-<timestamp>/``.

This is safe only when the existing motion already represents the exact same
temporal interval as the CoachClip. It cannot repair an asset extracted from
the full upload while the CoachClip represents ``startSec/endSec``. Those
assets must be regenerated by running LHM on the job's ``segment.mp4``.

Usage:
    python3 scripts/resample-motion-bin.py --confirm-same-interval <motion-dir> [...]
    python3 scripts/resample-motion-bin.py --confirm-same-interval --frames 150 <motion-dir> [...]

The target frame count defaults to the ``frames`` length of the CoachClip named
by the motion's ``record.json`` (``coachClipUrl``); ``--frames`` overrides it.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import tempfile
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from backend.avatar_assets import (  # noqa: E402
    resample_motion_frames,
    unpack_motion_asset,
    write_motion_asset,
)

BACKUP_ROOT = Path.home() / ".local" / "share" / "kinex" / "motion-backups"


def _coach_frame_count(record: dict, motion_dir: Path) -> int:
    url = record.get("coachClipUrl")
    if not isinstance(url, str) or not url:
        raise ValueError(f"{motion_dir}: record.json has no coachClipUrl; pass --frames")
    repo_root = motion_dir.resolve().parents[3]
    coach_path = (repo_root / url).resolve()
    if not coach_path.is_relative_to(repo_root) or not coach_path.is_file():
        raise ValueError(f"{motion_dir}: coach clip not found at {url}")
    clip = json.loads(coach_path.read_text(encoding="utf-8"))
    frames = clip.get("frames")
    if not isinstance(frames, list) or not frames:
        raise ValueError(f"{coach_path} contains no frames")
    return len(frames)


def _write_json_atomic(path: Path, record: dict) -> None:
    temp_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False
        ) as handle:
            temp_name = handle.name
            json.dump(record, handle, separators=(",", ":"), allow_nan=False)
            handle.flush()
            os.fsync(handle.fileno())
        Path(temp_name).replace(path)
    except Exception:
        if temp_name:
            Path(temp_name).unlink(missing_ok=True)
        raise


def resample_motion_dir(motion_dir: Path, target_frames: int | None) -> None:
    motion_dir = motion_dir.resolve()
    motion_path = motion_dir / "motion.bin"
    record_path = motion_dir / "record.json"
    if not motion_path.is_file():
        raise FileNotFoundError(motion_path)
    if not record_path.is_file():
        raise FileNotFoundError(record_path)

    record = json.loads(record_path.read_text(encoding="utf-8"))
    if not isinstance(record, dict):
        raise ValueError(f"{record_path} must contain a JSON object")
    target = target_frames if target_frames is not None else _coach_frame_count(record, motion_dir)

    meta, rotations, trans = unpack_motion_asset(motion_path)
    source_frames = int(rotations.shape[0])
    if source_frames == target:
        print(f"{motion_dir.name}: already {target} frames, nothing to do")
        return

    backup_dir = BACKUP_ROOT / f"{motion_dir.name}-{time.strftime('%Y%m%d-%H%M%S')}"
    backup_dir.mkdir(parents=True, exist_ok=False)
    shutil.copy2(motion_path, backup_dir / "motion.bin")
    shutil.copy2(record_path, backup_dir / "record.json")

    resampled_rotations, resampled_trans = resample_motion_frames(rotations, trans, target)
    write_motion_asset(motion_path, meta, resampled_rotations, resampled_trans)

    record["frameCount"] = target
    _write_json_atomic(record_path, record)
    print(f"{motion_dir.name}: {source_frames} -> {target} frames (backup: {backup_dir})")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("motion_dirs", nargs="+", type=Path, help="motion asset directories")
    parser.add_argument("--frames", type=int, default=None, help="override target frame count")
    parser.add_argument(
        "--confirm-same-interval",
        action="store_true",
        help="confirm motion.bin and CoachClip already cover the same temporal interval",
    )
    args = parser.parse_args()
    if args.frames is not None and args.frames < 1:
        parser.error("--frames must be a positive integer")
    if not args.confirm_same_interval:
        parser.error(
            "frame normalization cannot repair a full-upload/cropped-clip mismatch; "
            "rerun LHM on segment.mp4, or pass --confirm-same-interval when the intervals already match"
        )
    for motion_dir in args.motion_dirs:
        resample_motion_dir(motion_dir, args.frames)
    return 0


if __name__ == "__main__":
    sys.exit(main())
